name: Build and deploy Python app to Railway

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    container: ghcr.io/railwayapp/cli:latest  # Usamos el contenedor oficial de Railway CLI
    env:
      SVC_ID: '8b3ee3fb-35d3-4e68-8f23-69a8f9d23761'  # Reemplaza con el ID de tu servicio en Railway
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  # Secreto con tu token de Railway

    steps:
      - uses: actions/checkout@v3  # Esto es necesario para obtener el código
      - run: railway up --service=${{ env.SVC_ID }}  # Despliegue usando Railway CLI
